apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: customproject2
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'dev'
    server: '*'
  sourceRepos:
  - 'https://github.com/Unthink-pri18/Agro-Beg.git'
                 