apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: resource-project
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: "*"
    kind: 'Deployement'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - 'https://github.com/Unthink-pri18/Agro-Beg.git'
                 